name: WGFlyFlag
authors: [ mewin, xtechgamer735 ]
version: 0.4
main: com.mewin.wgFlyFlag.WGFlyFlagPlugin
depend: [ WorldGuard, WGCustomFlags ]
softdepend: [ WorldEdit ]

permissions:
  flyflag.ignore:
    description: ignore the fly flag
    default: false