name: WGFlyFlag
authors: [ mewin ]
version: "${project.version}"
main: com.mewin.wgFlyFlag.WGFlyFlagPlugin
depend: [ WorldGuard, WGCustomFlags ]
softdepend: [ WorldEdit ]

permissions:
  flyflag.ignore:
    description: ignore the fly flag
    default: false